#! /usr/bin/env python
from telegram.ext import Updater
from apitoken import apitoken, my_user_id
from telegram.ext import CommandHandler, MessageHandler, Filters
from collections import defaultdict
from validate_email import validate_email
import re
import logging
import argparse
import db
from cStringIO import StringIO
import datetime

config = defaultdict(dict)
logging.basicConfig(
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        level=logging.INFO)
logger = logging.getLogger()
messages = defaultdict(list)


def parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument('-v',
                        help="increase verbosity",
                        action="count", dest="verb", default=0)
    parser.add_argument('-d',
                        help="SQLite database file",
                        action="store", dest="db", default=None)
    args = parser.parse_args()

    if args.verb:
        logger.setLevel((50 - args.verb*10))

    if args.db:
        db.setup_db(args.db)
    else:
        db.setup_db(":memory:")


def parsemail(mail_string):
    logging.debug("Parsing string: %s" % mail_string)
    email_re = re.search(r"([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.])",
                         mail_string)
    if email_re:
        email = email_re.group()
        if validate_email(email):
            logging.debug("Extraced valid email %s" % email)
            return email

    logging.debug("Could not extrac valid email %s" % mail_string)
    return ''


def start(bot, update):
    bot.sendMessage(chat_id=update.message.chat_id,
                    text="Hello, if you include me as an admin "
                         "to a telegram group, i will read all "
                         "the messages and send a daily digest "
                         "in a mailing list of your choice.")
    if update.message.chat_id not in config:
        config[update.message.chat_id] = {'name': update.message.chat.title,
                                          'mailinglist': '', 'from': ''}


def dumpconfig(bot, update):
    for k, v in config.items():
        print k
        for kk, vv in config[k].items():
            print kk, ":", vv
    for chat_id, v in messages.items():
        print chat_id
        for msg in v:
            print " ", msg


def mailinglist(bot, update):
    logging.debug("Received message: " + str(update))
    email = parsemail(update.message.text)
    if email:
        db.savemailinglist(update.message.chat_id, email,
                           update.message.chat.title)
        bot.sendMessage(chat_id=update.message.chat_id,
                        text="OK, " + email +
                             "was saved as the mailinglist address")
    else:
        bot.sendMessage(chat_id=update.message.chat_id,
                        text="Not OK: " + update.message.text +
                             " is not a valid address")


def fromaddress(bot, update):
    logging.debug("Received message: " + str(update))
    email = parsemail(update.message.text)
    if email:
        db.savefromaddress(update.message.chat_id, email,
                           update.message.chat.title)
        bot.sendMessage(chat_id=update.message.chat_id,
                        text="OK, " + email +
                             "was saved as the from address")
    else:
        bot.sendMessage(chat_id=update.message.chat_id,
                        text="Not OK: " + update.message.text +
                             " is not a valid address")


def messagehandler(bot, update):

    if update.message.new_chat_member:
        if update.message.new_chat_member.id == my_user_id:
            db.savegroup(update.message.chat_id, update.message.chat.title)
    elif update.message.left_chat_member:
        if update.message.left_chat_member.id == my_user_id:
            db.delgroup(update.message.chat_id)
    elif update.message.chat.type == "group":
        db.savemessage(update.message.chat_id,
                       update.message.from_user.username,
                       update.message.text, update.message.chat.title,
                       update.message.from_user.id)


def prettyprintleft(l, u, d, s):
    left_margin = 32  # max username width
    if d:
        print >> s, ""
        print >> s, d[:left_margin-1].ljust(left_margin+1)
    print >> s, u.rjust(left_margin+1),
    line_width = 40
    first_line = l[0:line_width]
    print >> s, "|", first_line.ljust(line_width), "|"
    for line in [l[i:i+line_width] for i in range(line_width, len(l), line_width)]:
        print >> s, "".ljust(left_margin+1), "|", line.ljust(line_width), "|"


def prettyprintright(l, u, d, s):
    left_margin = 32  # max username width
    if d:
        print >> s, ""
        print >> s, d[:left_margin-1].ljust(left_margin+1)
    print >> s, "".rjust(left_margin+1),
    line_width = 40
    first_line = l[0:line_width]
    print >> s, "|", first_line.ljust(line_width), "|", u
    for line in [l[i:i+line_width] for i in range(line_width, len(l), line_width)]:
        print >> s, "".ljust(left_margin+1), "|", line.ljust(line_width), "|"


def dumpmessages(bot, update):
    chat_id = update.message.chat.id
    msgs = db.dumpmessages(chat_id)
    s = StringIO()
    left = True
    if len(msgs):
        prettyprintleft(msgs[0][2], msgs[0][0], str(msgs[0][1]), s)
    if len(msgs) > 1:
        for i in range(1, len(msgs)):
            if msgs[i-1][0] != msgs[i][0]:
                left = not left
            if msgs[i][1] - msgs[i-1][1] > datetime.timedelta(0, 300):
                datesent = str(msgs[i][1])
                print "Y", msgs[i][1] - msgs[i-1][1]
            else:
                print "X", msgs[i][1] - msgs[i-1][1]
                datesent = ""

            if left:
                prettyprintleft(msgs[i][2], msgs[i][0], datesent, s)
            else:
                prettyprintright(msgs[i][2], msgs[i][0], datesent, s)

    print s.getvalue()


def unknown(bot, update):
        bot.sendMessage(chat_id=update.message.chat_id,
                        text="Sorry, I didn't understand that command.")


parse_arguments()
updater = Updater(token=apitoken)
dispatcher = updater.dispatcher


start_handler = CommandHandler('start', start)
dispatcher.add_handler(start_handler)
mailinglist_handler = CommandHandler('mailinglist', mailinglist)
dispatcher.add_handler(mailinglist_handler)
fromaddress_handler = CommandHandler('from', fromaddress)
dispatcher.add_handler(fromaddress_handler)
dumpconfig_handler = CommandHandler('dumpconfig', dumpconfig)
dispatcher.add_handler(dumpconfig_handler)
dumpmessages_handler = CommandHandler('messages', dumpmessages)
dispatcher.add_handler(dumpmessages_handler)

unknown_handler = MessageHandler(Filters.command, unknown)
dispatcher.add_handler(unknown_handler)

message_handler = MessageHandler(Filters.all, messagehandler)
dispatcher.add_handler(message_handler)

updater.start_polling()
updater.idle()

db.close_db()
